import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { getTokens } from './api/getTokens';

export default function Home({ tokens }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 >THE SYSTEM</h1>
        <div className={styles.grid}>
          {tokens.map((token) => (
            <div key={token.id} className={styles.card}>
              <h3>
                Card {token.identifier}
              </h3>
              <p>
                Current Supply: {token.totalSupply.valueExact}
              </p>
              <p>
                Transfers: {token.transfers.reduce(function (tot, arr) {
                  if ((arr.to != null) && (arr.from != null)) { return tot + parseInt(arr.valueExact) }
                  else { return tot }
                }, 0)}
              </p>
              <p>
                Minted: {token.transfers.reduce(function (tot, arr) {
                  if (arr.from == null) { return (tot + parseInt(arr.valueExact)) }
                  else { return tot }
                }, 0)}
              </p>
              <p>
                Burned: {token.transfers.reduce(function (tot, arr) {
                  if (arr.to == null) { return tot + parseInt(arr.valueExact) }
                  else { return tot }
                }, 0)}
              </p>
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps() {
  return getTokens()
}


